---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: techtrends
  template: 
    metadata: 
      labels: 
        app: techtrends
    spec: 
      containers: 
        - 
          image: "julianafogg/techtrends:latest"
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: 3111
            initialDelaySeconds: 3
            periodSeconds: 3
          name: techtrends
          ports: 
            - 
              containerPort: 3111
          readinessProbe: 
            httpGet: 
              path: /healthz
              port: 3111
            initialDelaySeconds: 3
            periodSeconds: 3
          resources: 
            limits: 
              cpu: 500m
              memory: 128Mi
            requests: 
              cpu: 250m
              memory: 64Mi
status: {}


